name = "Kaggle Protein"

[files]
TRAIN_DIR = "./data/train"
TEST_DIR = "./data/test"
TRAIN_FILE = "train_sequences.fasta"
TRAIN_TERMS_FILE = "train_terms.tsv"
TEST_FILE = "test_superset.fasta"

[gene-ontology]
GO_FILE = "./data/extras/go-basic.obo"
NAMESPACES = {'biological_process'=0, 'molecular_function'=1, 'cellular_component'=2}
