name = "Kaggle Protein"

[files]
TRAIN_SEQ = "./data/train/train_sequences.fasta"
TRAIN_LAB = "./data/train/train_terms.tsv"
TEST_SEQ = "./data/test/testsuperset.fasta"
IA = "./data/extras/IA.txt"
EMBEDS = "./data/embeds.pkl"
EMBEDS_TEST = "./data/embeds_test.pkl"
SUBMIT = "./submit"

[gene-ontology]
GO_FILE = "./data/extras/go-basic.obo"
NAMESPACES = {'BP'='biological_process', 'MF'='molecular_function', 'CC'='cellular_component'}

[dataset]
MIN_PROTEINS = 100
N_FOLDS = 10
MAX_SEQ_LEN = 2048

[train]
MINI_BATCH_SIZE = 8
TEST_BATCH_SIZE = 8
ACCUMULATE = 4#32//MINI_BATCH_SIZE
LR = 1e-3
EPOCHS = 50

[model]
HIDDEN_DIM = 1024
BERT = "Rostlab/prot_bert"
