name = "Kaggle Protein"

[files]
TRAIN_SEQ = "./data/train/train_sequences.fasta"
TRAIN_LAB = "./data/train/train_terms.tsv"
TEST_SEQ = "./data/test/test_superset.fasta"

[gene-ontology]
GO_FILE = "./data/extras/go-basic.obo"
NAMESPACES = {'biological_process'=0, 'molecular_function'=1, 'cellular_component'=2}
