name = "Kaggle Protein KNN"

[files]
IA = "./data/extras/IA.txt"
TRAIN_LAB = "./data/train/train_terms.tsv"
EMBEDS =      "./data/embeddings/ESM_embeds_train.pkl"
EMBEDS_TEST = "./data/embeddings/ESM_embeds_test.pkl"

SUBMIT = "./submit/files"

[gene-ontology]
GO_FILE = "./data/extras/go-basic.obo"
NAMESPACES = {'BP'='biological_process', 'MF'='molecular_function', 'CC'='cellular_component'}

[train]
K = 11
