name = "Kaggle Protein"

[files]
TRAIN_SEQ = "./data/train/train_sequences.fasta"
TRAIN_LAB = "./data/train/train_terms.tsv"
TEST_SEQ = "./data/test/testsuperset.fasta"

[gene-ontology]
GO_FILE = "./data/extras/go-basic.obo"
NAMESPACES = {'BP'='biological_process', 'MF'='molecular_function', 'CC'='cellular_component'}

[dataset]
MIN_PROTEINS = 100
SUB_GRAPHS = ['CC','MF','BP']
N_FOLDS = 10
MAX_SEQ_LEN = 2048

[train]
BATCH_SIZE = 2
LR = 1e-5
EPOCHS = 3

[model]
HIDDEN_DIM = 1024
